/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceIntakeRouteImport } from './routes/voice-intake'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as IndexRouteImport } from './routes/index'

const VoiceIntakeRoute = VoiceIntakeRouteImport.update({
  id: '/voice-intake',
  path: '/voice-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/confirm': typeof ConfirmRoute
  '/report': typeof ReportRoute
  '/voice-intake': typeof VoiceIntakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/confirm': typeof ConfirmRoute
  '/report': typeof ReportRoute
  '/voice-intake': typeof VoiceIntakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/confirm': typeof ConfirmRoute
  '/report': typeof ReportRoute
  '/voice-intake': typeof VoiceIntakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calls' | '/confirm' | '/report' | '/voice-intake'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calls' | '/confirm' | '/report' | '/voice-intake'
  id: '__root__' | '/' | '/calls' | '/confirm' | '/report' | '/voice-intake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  ConfirmRoute: typeof ConfirmRoute
  ReportRoute: typeof ReportRoute
  VoiceIntakeRoute: typeof VoiceIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-intake': {
      id: '/voice-intake'
      path: '/voice-intake'
      fullPath: '/voice-intake'
      preLoaderRoute: typeof VoiceIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  ConfirmRoute: ConfirmRoute,
  ReportRoute: ReportRoute,
  VoiceIntakeRoute: VoiceIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
